name: "test"
description: "test action"
author: "didof <didonato.fr@gmail.com>"

inputs:
  milliseconds:
    description: number of milliseconds to wait
    required: false
    default: '1000'

outputs:
  time:
    description: 'The time after waiting'

runs:
  using: 'node16'
  main: '/actions/wait.js'

branding:
  icon: 'activity'  
  color: 'green'